FROM quay.io/katonic/katonic-base-images:py38-base-conda4.9.2

COPY app.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

CMD demo.launch(share=False, debug=True, server_port=8050, server_name="0.0.0.0")